# https://pnpm.io/blog/2025/12/05/newsroom-npm-supply-chain-security

strictDepBuilds: true

onlyBuiltDependencies:
  - package-with-necessary-build-scripts

ignoredBuiltDependencies:
  - package-with-unnecessary-build-scripts

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - package-with-critical-hotfix@1.2.3

trustPolicy: no-downgrade

trustPolicyExclude:
  - package-that-migrated-cicd@1.2.3
